/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Order {
  'id' : bigint,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'buyerProfileSnapshot' : UserProfile,
  'productSnapshot' : Product,
  'buyerPrincipal' : Principal,
  'shippingAddress' : Address,
}
export type PaymentMethod = { 'creditCard' : string } |
  { 'cashOnDelivery' : null } |
  { 'bankTransfer' : string } |
  { 'paypal' : string };
export interface Product {
  'id' : bigint,
  'sellerPrincipal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'imageUrl' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'role' : { 'seller' : null } |
    { 'buyer' : null },
  'shippingAddress' : [] | [Address],
  'phoneNumber' : [] | [string],
  'paymentMethods' : Array<PaymentMethod>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[bigint, Address, PaymentMethod], Order>,
  'createProduct' : ActorMethod<[string, bigint, string], Product>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listMyProducts' : ActorMethod<[], Array<Product>>,
  'listOrdersForMyProducts' : ActorMethod<[], Array<Order>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];