/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Text,
  'cashOnDelivery' : IDL.Null,
  'bankTransfer' : IDL.Text,
  'paypal' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'role' : IDL.Variant({ 'seller' : IDL.Null, 'buyer' : IDL.Null }),
  'shippingAddress' : IDL.Opt(Address),
  'phoneNumber' : IDL.Opt(IDL.Text),
  'paymentMethods' : IDL.Vec(PaymentMethod),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sellerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'buyerProfileSnapshot' : UserProfile,
  'productSnapshot' : Product,
  'buyerPrincipal' : IDL.Principal,
  'shippingAddress' : Address,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([IDL.Nat, Address, PaymentMethod], [Order], []),
  'createProduct' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Product], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listOrdersForMyProducts' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Text,
    'cashOnDelivery' : IDL.Null,
    'bankTransfer' : IDL.Text,
    'paypal' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'role' : IDL.Variant({ 'seller' : IDL.Null, 'buyer' : IDL.Null }),
    'shippingAddress' : IDL.Opt(Address),
    'phoneNumber' : IDL.Opt(IDL.Text),
    'paymentMethods' : IDL.Vec(PaymentMethod),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sellerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'buyerProfileSnapshot' : UserProfile,
    'productSnapshot' : Product,
    'buyerPrincipal' : IDL.Principal,
    'shippingAddress' : Address,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([IDL.Nat, Address, PaymentMethod], [Order], []),
    'createProduct' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Product], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listOrdersForMyProducts' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };